In [1]:
import numpy as np

NumPy is a powerful Python library used for scientific computing. It provides a high-performance multidimensional array object, and tools for working with these arrays.

Here are some of the use cases of NumPy:

* **Scientific and technical computing:** NumPy is widely used in scientific and technical computing, including fields such as physics, engineering, and data analysis. It provides efficient tools for manipulating and analyzing large datasets.
* **Data analysis and visualization:** NumPy is commonly used for data analysis and visualization tasks. It offers various functions for manipulating and analyzing data, as well as for creating plots and visualizations.
* **Machine learning and artificial intelligence:** NumPy is a fundamental library for machine learning and artificial intelligence applications. It provides efficient data structures and algorithms for training and evaluating machine learning models.
* **Image and signal processing:** NumPy is widely used for image and signal processing tasks. It offers various functions for manipulating and analyzing images and signals.


In [2]:
my_lst=[1,2,3,4,5,6,7,8,9,0]

In [3]:
arr=np.array(my_lst)

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(10,)

In [12]:
arr= arr.reshape(2,5)

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [13]:
arr.shape

(2, 5)

In [15]:
arr[1:2]

array([[6, 7, 8, 9, 0]])

In [24]:
arr=np.arange(0,12,2)

In [25]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [26]:
arr[3:]

array([ 6,  8, 10])

In [29]:
arr1=np.linspace(10,100,20)

In [30]:
arr1

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

In [31]:
arr1[3:]=30

In [33]:
arr1

array([10.        , 14.73684211, 19.47368421, 30.        , 30.        ,
       30.        , 30.        , 30.        , 30.        , 30.        ,
       30.        , 30.        , 30.        , 30.        , 30.        ,
       30.        , 30.        , 30.        , 30.        , 30.        ])

In [34]:
arr1*2

array([20.        , 29.47368421, 38.94736842, 60.        , 60.        ,
       60.        , 60.        , 60.        , 60.        , 60.        ,
       60.        , 60.        , 60.        , 60.        , 60.        ,
       60.        , 60.        , 60.        , 60.        , 60.        ])

In [35]:
arr1%2

array([0.        , 0.73684211, 1.47368421, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [36]:
arr1[arr1<15]

array([10.        , 14.73684211])

In [37]:
np.random.rand(4,4)

array([[0.66780673, 0.69291465, 0.62822922, 0.92206843],
       [0.58347587, 0.30504481, 0.33682252, 0.77889459],
       [0.79594486, 0.33946994, 0.10444296, 0.8737716 ],
       [0.74635125, 0.85416347, 0.67287498, 0.18944922]])

In [38]:
np.random.randn(4,4)

array([[-0.10879081, -1.04833312,  0.73558631, -0.05244388],
       [-2.40907033,  0.39142513,  2.73912074,  1.45206825],
       [ 0.93128818,  0.56979517, -0.41042796, -2.44351319],
       [ 0.02349246, -0.2378009 , -0.73078994, -0.65184395]])